// <auto-generated />
using System;
using GekkoLab.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GekkoLab.Migrations
{
    [DbContext(typeof(GekkoLabDbContext))]
    [Migration("20260124000000_AddWeatherReadings")]
    partial class AddWeatherReadings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("GekkoLab.Models.SensorReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<double>("Humidity")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsValid")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Pressure")
                        .HasColumnType("REAL");

                    b.Property<double>("Temperature")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.ToTable("SensorReadings");
                });

            modelBuilder.Entity("GekkoLab.Models.SystemMetrics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CpuUsagePercent")
                        .HasColumnType("REAL");

                    b.Property<double>("DiskUsagePercent")
                        .HasColumnType("REAL");

                    b.Property<long>("DiskTotalBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DiskUsedBytes")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MemoryUsagePercent")
                        .HasColumnType("REAL");

                    b.Property<long>("MemoryTotalBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MemoryUsedBytes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.ToTable("SystemMetrics");
                });

            modelBuilder.Entity("GekkoLab.Models.WeatherReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Humidity")
                        .HasColumnType("REAL");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<double>("Temperature")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.ToTable("WeatherReadings");
                });

            modelBuilder.Entity("GekkoLab.Models.SensorReading", b =>
                {
                    b.OwnsOne("GekkoLab.Models.SensorMetadata", "Metadata", b1 =>
                        {
                            b1.Property<int>("SensorReadingId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("ReaderType")
                                .HasColumnType("TEXT")
                                .HasDefaultValue("unknown");

                            b1.HasKey("SensorReadingId");

                            b1.ToTable("SensorReadings");

                            b1.WithOwner()
                                .HasForeignKey("SensorReadingId");
                        });

                    b.Navigation("Metadata");
                });
#pragma warning restore 612, 618
        }
    }
}
