// <auto-generated />
using System;
using GekkoLab.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GekkoLab.Migrations
{
    [DbContext(typeof(GekkoLabDbContext))]
    partial class GekkoLabDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("GekkoLab.Models.SensorReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<double>("Humidity")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsValid")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Pressure")
                        .HasColumnType("REAL");

                    b.Property<double>("Temperature")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.ToTable("SensorReadings");
                });

            modelBuilder.Entity("GekkoLab.Models.SensorReading", b =>
                {
                    b.OwnsOne("GekkoLab.Models.SensorMetadata", "Metadata", b1 =>
                        {
                            b1.Property<int>("SensorReadingId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("ReaderType")
                                .HasColumnType("TEXT");

                            b1.HasKey("SensorReadingId");

                            b1.ToTable("SensorReadings");

                            b1.WithOwner()
                                .HasForeignKey("SensorReadingId");
                        });

                    b.Navigation("Metadata");
                });
#pragma warning restore 612, 618
        }
    }
}
